<?php
/**
 * ColorDepth
 *
 * PHP version 5
 *
 * @category Class
 * @package  Aspose\PDF
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Aspose.PDF for Cloud API Reference
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.3.1
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Aspose\PDF\Model;
use \Aspose\PDF\ObjectSerializer;

/**
 * ColorDepth Class Doc Comment
 *
 * @category Class
 * @description Used to specify the parameter value passed to a Tiff image device.
 * @package  Aspose\PDF
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class ColorDepth
{
    /**
     * Possible values of this enum
     */
    const _DEFAULT = 'Default';
    const FORMAT8BPP = 'Format8bpp';
    const FORMAT4BPP = 'Format4bpp';
    const FORMAT1BPP = 'Format1bpp';
    
    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::_DEFAULT,
            self::FORMAT8BPP,
            self::FORMAT4BPP,
            self::FORMAT1BPP,
        ];
    }
}


