<?php
/**
 * CompressionType
 *
 * PHP version 5
 *
 * @category Class
 * @package  Aspose\PDF
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Aspose.PDF for Cloud API Reference
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.3.1
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Aspose\PDF\Model;
use \Aspose\PDF\ObjectSerializer;

/**
 * CompressionType Class Doc Comment
 *
 * @category Class
 * @description Used to specify the parameter value passed to a Tiff image device.
 * @package  Aspose\PDF
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class CompressionType
{
    /**
     * Possible values of this enum
     */
    const LZW = 'LZW';
    const CCITT4 = 'CCITT4';
    const CCITT3 = 'CCITT3';
    const RLE = 'RLE';
    const NONE = 'None';
    
    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::LZW,
            self::CCITT4,
            self::CCITT3,
            self::RLE,
            self::NONE,
        ];
    }
}


