<?php
/**
 * WrapMode
 *
 * PHP version 5
 *
 * @category Class
 * @package  Aspose\PDF
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Aspose.PDF for Cloud API Reference
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.3.1
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Aspose\PDF\Model;
use \Aspose\PDF\ObjectSerializer;

/**
 * WrapMode Class Doc Comment
 *
 * @category Class
 * @description 
 * @package  Aspose\PDF
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class WrapMode
{
    /**
     * Possible values of this enum
     */
    const NO_WRAP = 'NoWrap';
    const BY_WORDS = 'ByWords';
    const DISCRETIONARY_HYPHENATION = 'DiscretionaryHyphenation';
    
    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::NO_WRAP,
            self::BY_WORDS,
            self::DISCRETIONARY_HYPHENATION,
        ];
    }
}


